version: "3"
services:
  app:
    build: .
    command: node build/main.js
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ${PWD}/prisma/db:/app/prisma/db
      - ${WPD}/token.json:/app/token.json
